Repository DUNE-DAQ/nanorc, pull requests merged in 2024-03, with the labels that each got.

#251 Catch for SIGQUIT
  src/nanorc/__main__.py
  src/nanorc/__main_np04__.py
  src/nanorc/__main_timing__.py
  src/nanorc/utils.py
Labels: miscellaneous deliverable

#252 Fix for incorrect user or password
  src/nanorc/credmgr.py
Labels: miscellaneous deliverable

#253 Modifications to make use of a new StartParams field (`production_vs_test`)
  src/nanorc/cli.py
  src/nanorc/core.py
Labels: deliverable subtask

#255 ELisA message format
  src/nanorc/core.py
  src/nanorc/logbook.py
  src/nanorc/treebuilder.py
Labels: miscellaneous deliverable

#258 bugfix: Added default value for --run-type click option in cli.py
  src/nanorc/cli.py
Labels: bug, miscellaneous deliverable

#259 Make run type prod by default on nano04rc
  src/nanorc/__main_np04__.py
Labels: miscellaneous deliverable
